name: Trigger auto deployment for container-app-n7ppd2d2ameda

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-n7ppd2d2ameda-AutoDeployTrigger-0dd835b1-eaf5-4efd-b249-26a648898745.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPN7PPD2D2AMEDA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPN7PPD2D2AMEDA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPN7PPD2D2AMEDA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPN7PPD2D2AMEDA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPN7PPD2D2AMEDA_REGISTRY_PASSWORD }}
          containerAppName: container-app-n7ppd2d2ameda
          resourceGroup: appspacesragappb16c3333390e1
          imageToBuild: default/container-app-n7ppd2d2ameda:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


